theme:
    app:    "flexoki"
    syntax: "css"

keys:
    # Application
    "quit_app":           "Ctrl+Q"
    "show_help":          "F1"
    "command_palette":    "Ctrl+P"
    "open_settings":      ""
    "show_about":         ""
    # File operations
    "save":               "Ctrl+S"
    "trim_whitespace":    "Ctrl+T"
    "toggle_wrapping":    "Ctrl+L"
    # Clipboard interaction
    "cut":               "Ctrl+X"
    "copy":              "Ctrl+C"
    "paste":             "Ctrl+V"
    # Edit history
    "undo":              "Ctrl+Z"
    "redo":              "Ctrl+Y"
    # Cursor movement
    "cursor_up":         "Up"
    "cursor_down":       "Down"
    "cursor_left":       "Left"
    "cursor_right":      "Right"
    "cursor_word_left":  "Ctrl+Left"
    "cursor_word_right": "Ctrl+Right"
    "cursor_line_start": "Home"
    "cursor_line_end":   "End"
    "cursor_page_up":    "PageUp"
    "cursor_page_down":  "PageDown"
    "cursor_file_start": "Ctrl+Home"
    "cursor_file_end":   "Ctrl+End"
    # Text deletion
    "delete_left":       "Backspace"
    "delete_right":      "Delete"
    "delete_word_left":  "Ctrl+Backspace"
    "delete_word_right": "Ctrl+Delete"
    # Selections
    "select_left":       "Shift+Left"
    "select_right":      "Shift+Right"
    "select_word_left":  "Ctrl+Shift+Left"
    "select_word_right": "Ctrl+Shift+Right"
    "select_line_start": "Shift+Home"
    "select_line_end":   "Shift+End"
    "select_line_up":    "Shift+Up"
    "select_line_down":  "Shift+Down"
    "select_all":        "Ctrl+A"
